server:
  port: ${server-port:8761}
   
spring:
  application.name: ${springboot.app.name:eureka-serviceregistry}
  #boot:
  #  admin:
  #    context-path: /admin

eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int} 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS
logging:
  pattern.console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n"

