zuul:
   prefix: /api
   #sensitiveHeaders: Cookie,Set-Cookie,Authorization
   sensitiveHeaders:
   retryable: false
   add-host-header: true
ribbon:
   ReadTimeout: 15000
   ConnectTimeout: 5000
   SocketTimeout: 15000
hystrix:
   command:
      myusers-service:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 15000
eureka:
   instance:
     prefer-ip-address: true
     leaseRenewalIntervalInSeconds: 10
     health-check-url-path: /actuator/health
     metadata-map:
       startup: ${random.int} 
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
         #defaultZone: http://host1:8761/eureka/,http://host2:8761/eureka/,http://host3:8761/eureka/
      healthcheck:
         enabled: true
      lease:
         duration: 5

